### ISSUE TITLE
footerが重なる問題

### ISSUE THREAD

**Issue by Fenotasu** [Fenotasu/yumeguri_app#2]
"https://webkikaku.co.jp/blog/htmlcss/footer-bottom/" このサイトを参考に投稿一覧の数が増えてもfooterを下に固定できるようにしたんですが、最下部の投稿とfooterが思いっきり重なります。
footerのmarign-topを設定したり、bodyのmargin-bottomを設定しましたが重なるだけで効果なしです。
引き続き模索します。

**Comment by shunsuke-i-anotelia** [comment]
footerタグはbodyタグの中ですね。
bodyに`position: absolute;`をつけ、footerに`position: relative; bottom:0;`を付けてみてください。
そうするとbody要素の下辺にくっつくようになると思います。

加えて`views/lists/show.html.erb`にDOCTYPEやhtmlタグがありますが不要です。
画面確認していませんが、タイトル(ブラウザのタブに表示される文言)が、show.html.erbに設定している「温泉巡り」ではなく「YumeguriApp」と出ているのではないでしょうか。
Railsの画面仕様として、`views/layouts/application.html.erb`が土台になり`<%= yield %>`に中身、今回の画面では`show.html.erb`のコードが書き込まれるようになっています！

**Comment by Fenotasu** [comment]
>加えてviews/lists/show.html.erbにDOCTYPEやhtmlタグがありますが不要です。
home,listsグループのhtmlからはすべてdoctype,HTMLタグを消して、layouts/application.html.erbのtitleを書き直したら正しく表示されるようになりました！
ありがとうございます！

**Comment by Fenotasu** [comment]
`bodyにposition: absolute;をつけ、footerにposition: relative; bottom:0;を付けてみてください。`
を試してみたんですが、一旦綺麗になりましたが投稿が増えるとやはり埋もれてしまいます。footerのheightを１００％にするとおかしなことになるし、投稿の数に合わせて高さを変えていく方法を探します

**Comment by Fenotasu** [comment]
【問題】投稿一覧画面でfooterをbodyクラスの子要素にして、position:relative bottom:0にしているにも関わらず、 投稿内容の大きさを無視して一番上に表示される

【原因】投稿一覧のスタイルでfloatが設定してあったため、bodyタグの中に表示されるのがfooterのみになり、bodyのスタイルがheight:100% だったため、footerの大きさと同じになり、一番上に表示されていた。
